/* GENERATED by scripts/abi/abigen.py from abi/idl/abi_selftest.world.json - do not edit; change the IDL and regenerate */
#ifndef EDEN_ABI_ABI_SELFTEST_H
#define EDEN_ABI_ABI_SELFTEST_H

#include <stdint.h>
#include "eden_game.h"
#include "abi_test.h"

/* World abi_selftest, version 1: The eden_game world plus the abi_test package and exports of every argument type: the round-trip guest of the ABI test suite. The guest defines the exports below. */

#define ABI_SELFTEST_VERSION 1

/* Calls every import of abi_test and eden_core with known values and checks the answers; returns the number of mismatches. */
__attribute__((export_name("selftest_run_imports")))
int32_t selftest_run_imports(void);

/* Returns the byte length of s plus 1000 * its first byte (0 when empty). */
__attribute__((export_name("selftest_take_str")))
int32_t selftest_take_str(const char *s, int32_t s_len);

/* Returns the sum of the bytes of b. */
__attribute__((export_name("selftest_take_bytes")))
int32_t selftest_take_bytes(const void *b, int32_t b_len);

/* Returns a + b + c + d + (e ? 1 : 0) as f64. */
__attribute__((export_name("selftest_scalars")))
double selftest_scalars(int32_t a, int64_t b, float c, double d, int32_t e);

/* Returns v * 3. */
__attribute__((export_name("selftest_i64")))
int64_t selftest_i64(int64_t v);

/* Returns v * 0.5. */
__attribute__((export_name("selftest_f32")))
float selftest_f32(float v);

/* Calls abi_test.fail, which traps; never returns normally. */
__attribute__((export_name("selftest_trap")))
int32_t selftest_trap(void);

/* Passes a bad argument to an import: 0 = a str range past linear memory, 1 = bytes with a negative length, 2 = a str holding a NUL byte. Each must trap in the host wrapper. */
__attribute__((export_name("selftest_bad_pointer")))
int32_t selftest_bad_pointer(int32_t which);

/* Exercises eden_storage directly (every error code but ERR_FULL and ERR_IO) and through the libc file modes (w, r, a, remove); leaves the blob `keep` (5 bytes: keep!) behind. Returns the number of mismatches. */
__attribute__((export_name("selftest_storage")))
int32_t selftest_storage(void);

/* eden_storage.size of the blob as the guest sees it. */
__attribute__((export_name("selftest_blob_size")))
int32_t selftest_blob_size(const char *name, int32_t name_len);

/* Calls abi_test.record("reenter"); the host implementation tries to call back into the guest there. */
__attribute__((export_name("selftest_reenter")))
int32_t selftest_reenter(void);

/* Not implemented by the guest on purpose: an optional export the host must see as absent. (optional) */
__attribute__((export_name("selftest_missing")))
int32_t selftest_missing(void);

#endif
