/* GENERATED by scripts/abi/abigen.py from abi/idl/abi_test.json - do not edit; change the IDL and regenerate */
#ifndef EDEN_ABI_ABI_TEST_H
#define EDEN_ABI_ABI_TEST_H

#include <stdint.h>

/* Package abi_test, version 1: Test-only package: one import per ABI type, used by the self-test guest to prove marshalling in both directions. Never offered to a real guest. */

#define ABI_TEST_VERSION 1
#define ABI_TEST_MAGIC (1234567) /* a value both sides know */

/* Returns v. */
__attribute__((import_module("abi_test"), import_name("echo_i32")))
int32_t abi_test_echo_i32(int32_t v);

/* Returns v. */
__attribute__((import_module("abi_test"), import_name("echo_i64")))
int64_t abi_test_echo_i64(int64_t v);

/* Returns v. */
__attribute__((import_module("abi_test"), import_name("echo_f32")))
float abi_test_echo_f32(float v);

/* Returns v. */
__attribute__((import_module("abi_test"), import_name("echo_f64")))
double abi_test_echo_f64(double v);

/* Returns !v. */
__attribute__((import_module("abi_test"), import_name("negate")))
int32_t abi_test_negate(int32_t v);

/* Returns a + b + c + d + (e ? 1 : 0) as f64: arguments of every scalar type in one call. */
__attribute__((import_module("abi_test"), import_name("mix")))
double abi_test_mix(int32_t a, int64_t b, float c, double d, int32_t e);

/* Returns the byte length of s as the host received it. */
__attribute__((import_module("abi_test"), import_name("str_len")))
int32_t abi_test_str_len(const char *s, int32_t s_len);
static inline int32_t abi_test_str_len_z(const char *s) {
    return abi_test_str_len(s, (int32_t)__builtin_strlen(s));
}

/* Returns the sum of the bytes of b. */
__attribute__((import_module("abi_test"), import_name("bytes_sum")))
int32_t abi_test_bytes_sum(const void *b, int32_t b_len);

/* Writes byte i = (seed + i) & 255 for every i < cap of dst; returns cap. */
__attribute__((import_module("abi_test"), import_name("fill")))
int32_t abi_test_fill(void *dst, int32_t dst_cap, int32_t seed);

/* Creates a host object holding v; returns its handle. */
__attribute__((import_module("abi_test"), import_name("make_handle")))
int32_t abi_test_make_handle(int32_t v);

/* Value of the host object, or -1 for a bad handle. */
__attribute__((import_module("abi_test"), import_name("handle_value")))
int32_t abi_test_handle_value(int32_t h);

/* Always traps with the message `requested`. */
__attribute__((import_module("abi_test"), import_name("fail")))
void abi_test_fail(void);

/* Appends the string to the host's call log (the host test reads it). */
__attribute__((import_module("abi_test"), import_name("record")))
void abi_test_record(const char *s, int32_t s_len);
static inline void abi_test_record_z(const char *s) {
    abi_test_record(s, (int32_t)__builtin_strlen(s));
}

#endif
