/* GENERATED by scripts/abi/abigen.py from abi/idl/eden_storage.json - do not edit; change the IDL and regenerate */
#ifndef EDEN_ABI_EDEN_STORAGE_H
#define EDEN_ABI_EDEN_STORAGE_H

#include <stdint.h>

/* Package eden_storage, version 1: Persistent named blobs (save games, battery RAM, settings) that outlive the instance and the session. The host gives each guest its own namespace; the guest only names blobs inside it. A write replaces the whole blob and is persisted before it returns. */

#define EDEN_STORAGE_VERSION 1
#define EDEN_STORAGE_MAX_NAME (64) /* longest blob name in bytes */
#define EDEN_STORAGE_MAX_TOTAL_BYTES (3145728) /* all blobs of a namespace together (the Eden host keeps a namespace in one engine storage of at most 5 MB, base64-encoded) */
#define EDEN_STORAGE_OK (0) /* success */
#define EDEN_STORAGE_ERR_NOT_FOUND (-1) /* no blob with this name */
#define EDEN_STORAGE_ERR_RANGE (-2) /* offset is negative or past the end of the blob */
#define EDEN_STORAGE_ERR_FULL (-3) /* the write would take the namespace past MAX_TOTAL_BYTES */
#define EDEN_STORAGE_ERR_IO (-4) /* the host could not persist the change (engine storage limits or errors); the previous content is kept */
#define EDEN_STORAGE_ERR_NAME (-5) /* the name is empty or longer than MAX_NAME */

/* Size of the blob in bytes, or ERR_NOT_FOUND / ERR_NAME. */
__attribute__((import_module("eden_storage"), import_name("size")))
int32_t eden_storage_size(const char *name, int32_t name_len);
static inline int32_t eden_storage_size_z(const char *name) {
    return eden_storage_size(name, (int32_t)__builtin_strlen(name));
}

/* Copies bytes [offset, offset + cap) of the blob (fewer at its end) into dst. Returns the number of bytes copied, or ERR_NOT_FOUND / ERR_RANGE / ERR_NAME. */
__attribute__((import_module("eden_storage"), import_name("read")))
int32_t eden_storage_read(const char *name, int32_t name_len, int32_t offset, void *dst, int32_t dst_cap);
static inline int32_t eden_storage_read_z(const char *name, int32_t offset, void *dst, int32_t dst_cap) {
    return eden_storage_read(name, (int32_t)__builtin_strlen(name), offset, dst, dst_cap);
}

/* Replaces the blob with data (creating it) and persists it. Returns OK or ERR_FULL / ERR_IO / ERR_NAME. */
__attribute__((import_module("eden_storage"), import_name("write")))
int32_t eden_storage_write(const char *name, int32_t name_len, const void *data, int32_t data_len);
static inline int32_t eden_storage_write_z(const char *name, const void *data, int32_t data_len) {
    return eden_storage_write(name, (int32_t)__builtin_strlen(name), data, data_len);
}

/* Deletes the blob and persists the change. Returns OK or ERR_NOT_FOUND / ERR_IO / ERR_NAME. */
__attribute__((import_module("eden_storage"), import_name("remove")))
int32_t eden_storage_remove(const char *name, int32_t name_len);
static inline int32_t eden_storage_remove_z(const char *name) {
    return eden_storage_remove(name, (int32_t)__builtin_strlen(name));
}

#endif
