/* GENERATED by scripts/abi/abigen.py from abi/idl/eden_game.world.json - do not edit; change the IDL and regenerate */
#ifndef EDEN_ABI_EDEN_GAME_H
#define EDEN_ABI_EDEN_GAME_H

#include <stdint.h>
#include "eden_core.h"
#include "eden_asset.h"
#include "eden_video.h"
#include "eden_input.h"
#include "eden_audio.h"
#include "eden_storage.h"

/* World eden_game, version 1: A real-time program (game, emulator, demo) driven frame by frame by an Eden host. The guest defines the exports below. */

#define EDEN_GAME_VERSION 1
#define EDEN_GAME_STEP_FRAME (1) /* eden_step: a frame was presented during this step */
#define EDEN_GAME_STEP_QUIT (2) /* eden_step: the guest wants to stop */
#define EDEN_GAME_STEP_ERROR (4) /* eden_step: the guest failed and logged why */

/* The world version the guest was built for. */
__attribute__((export_name("eden_abi_version")))
int32_t eden_abi_version(void);

/* Allocates size bytes in linear memory; 0 on failure. */
__attribute__((export_name("eden_alloc")))
int32_t eden_alloc(int32_t size);

/* Frees a pointer from eden_alloc; 0 is ignored. */
__attribute__((export_name("eden_free")))
void eden_free(int32_t ptr);

/* Prepares the guest; 0 = ready, other values are the guest's error codes. */
__attribute__((export_name("eden_init")))
int32_t eden_init(void);

/* Works for about budget_us microseconds of host time; returns STEP_* flags. */
__attribute__((export_name("eden_step")))
int32_t eden_step(int32_t budget_us);

/* Releases everything; the instance is destroyed after it. */
__attribute__((export_name("eden_shutdown")))
void eden_shutdown(void);

/* Bytes needed by eden_state_save now. (optional) */
__attribute__((export_name("eden_state_size")))
int32_t eden_state_size(void);

/* Writes the snapshot to guest memory [dst, dst + cap); returns bytes written or a negative error. (optional) */
__attribute__((export_name("eden_state_save")))
int32_t eden_state_save(int32_t dst, int32_t cap);

/* Restores a snapshot made by eden_state_save of the same guest build; 0 = ok. (optional) */
__attribute__((export_name("eden_state_load")))
int32_t eden_state_load(const void *snapshot, int32_t snapshot_len);

#endif
