/* GENERATED by scripts/abi/abigen.py from abi/idl/eden_audio.json - do not edit; change the IDL and regenerate */
#ifndef EDEN_ABI_EDEN_AUDIO_H
#define EDEN_ABI_EDEN_AUDIO_H

#include <stdint.h>

/* Package eden_audio, version 1: Streaming PCM output. The guest opens a stream and pushes interleaved samples; the host plays them in order. */

#define EDEN_AUDIO_VERSION 1
#define EDEN_AUDIO_SAMPLE_S16 (0) /* signed 16-bit little-endian */
#define EDEN_AUDIO_SAMPLE_F32 (1) /* 32-bit float in [-1, 1] */
#define EDEN_AUDIO_SAMPLE_U8 (2) /* unsigned 8-bit, 128 = silence */
#define EDEN_AUDIO_MIN_RATE (8000) /* lowest sample rate */
#define EDEN_AUDIO_MAX_RATE (192000) /* highest sample rate */
#define EDEN_AUDIO_ERR_ARGS (-1) /* rate or channel count out of range, unknown format, or samples not a whole number of frames */
#define EDEN_AUDIO_ERR_HANDLE (-2) /* not an open stream of this instance */
#define EDEN_AUDIO_ERR_UNAVAILABLE (-3) /* the host has no audio output */

/* Opens a stream with `channels` (1 or 2) interleaved channels at `rate` Hz. Returns a stream handle (> 0) or ERR_*. */
__attribute__((import_module("eden_audio"), import_name("open")))
int32_t eden_audio_open(int32_t rate, int32_t channels);

/* Appends samples in `format` (SAMPLE_*). Returns the number of frames queued, or ERR_*. */
__attribute__((import_module("eden_audio"), import_name("push")))
int32_t eden_audio_push(int32_t stream, const void *samples, int32_t samples_len, int32_t format);

/* Frames pushed but not yet played, as far as the host can tell (for back-pressure); ERR_HANDLE for a bad handle. */
__attribute__((import_module("eden_audio"), import_name("queued")))
int32_t eden_audio_queued(int32_t stream);

/* Stops and releases the stream. A bad handle is ignored. */
__attribute__((import_module("eden_audio"), import_name("close")))
void eden_audio_close(int32_t stream);

#endif
