/* GENERATED by scripts/abi/abigen.py from abi/idl/eden_asset.json - do not edit; change the IDL and regenerate */
#ifndef EDEN_ABI_EDEN_ASSET_H
#define EDEN_ABI_EDEN_ASSET_H

#include <stdint.h>

/* Package eden_asset, version 1: Read-only named data files the host makes available to the guest (ROMs, WADs, levels). Names are host-defined keys, not file paths. */

#define EDEN_ASSET_VERSION 1
#define EDEN_ASSET_ERR_NOT_FOUND (-1) /* no asset with this name */
#define EDEN_ASSET_ERR_RANGE (-2) /* offset is negative or past the end of the asset */

/* Size of the asset in bytes, or ERR_NOT_FOUND. */
__attribute__((import_module("eden_asset"), import_name("size")))
int32_t eden_asset_size(const char *name, int32_t name_len);
static inline int32_t eden_asset_size_z(const char *name) {
    return eden_asset_size(name, (int32_t)__builtin_strlen(name));
}

/* Copies bytes [offset, offset + cap) of the asset (fewer at its end) into dst. Returns the number of bytes copied, or ERR_NOT_FOUND / ERR_RANGE. */
__attribute__((import_module("eden_asset"), import_name("read")))
int32_t eden_asset_read(const char *name, int32_t name_len, int32_t offset, void *dst, int32_t dst_cap);
static inline int32_t eden_asset_read_z(const char *name, int32_t offset, void *dst, int32_t dst_cap) {
    return eden_asset_read(name, (int32_t)__builtin_strlen(name), offset, dst, dst_cap);
}

#endif
