/* GENERATED by scripts/abi/abigen.py from abi/idl/eden_video.json - do not edit; change the IDL and regenerate */
#ifndef EDEN_ABI_EDEN_VIDEO_H
#define EDEN_ABI_EDEN_VIDEO_H

#include <stdint.h>

/* Package eden_video, version 1: A software framebuffer the host shows as a texture. */

#define EDEN_VIDEO_VERSION 1
#define EDEN_VIDEO_FORMAT_RGBA8 (0) /* 4 bytes per pixel in memory order R, G, B, A */
#define EDEN_VIDEO_FORMAT_RGB565 (1) /* 2 bytes per pixel, little-endian, red in the high 5 bits */
#define EDEN_VIDEO_FORMAT_INDEXED8 (2) /* 1 byte per pixel, an index into the palette set with set_palette */
#define EDEN_VIDEO_MAX_WIDTH (4096) /* largest accepted width */
#define EDEN_VIDEO_MAX_HEIGHT (4096) /* largest accepted height */
#define EDEN_VIDEO_OK (0) /* success */
#define EDEN_VIDEO_ERR_FORMAT (-1) /* unknown format */
#define EDEN_VIDEO_ERR_SIZE (-2) /* width, height or stride out of range, or pixels shorter than stride * height */
#define EDEN_VIDEO_ERR_PALETTE (-3) /* palette is not a whole number of RGBA8 entries, is empty, or has more than 256 */

/* Shows a frame. stride is the distance between rows in bytes. The host copies the pixels before returning. Returns OK or ERR_*. */
__attribute__((import_module("eden_video"), import_name("present")))
int32_t eden_video_present(const void *pixels, int32_t pixels_len, int32_t width, int32_t height, int32_t stride, int32_t format);

/* Sets the palette for FORMAT_INDEXED8: up to 256 RGBA8 entries. Missing entries are opaque black. Returns OK or ERR_PALETTE. */
__attribute__((import_module("eden_video"), import_name("set_palette")))
int32_t eden_video_set_palette(const void *colors, int32_t colors_len);

#endif
