/* GENERATED by scripts/abi/abigen.py from abi/idl/eden_core.json - do not edit; change the IDL and regenerate */
#ifndef EDEN_ABI_EDEN_CORE_H
#define EDEN_ABI_EDEN_CORE_H

#include <stdint.h>

/* Package eden_core, version 1: Logging, the host clock and fatal errors. */

#define EDEN_CORE_VERSION 1
#define EDEN_CORE_LOG_DEBUG (0) /* diagnostic detail */
#define EDEN_CORE_LOG_INFO (1) /* normal messages */
#define EDEN_CORE_LOG_WARN (2) /* something is off but the guest continues */
#define EDEN_CORE_LOG_ERROR (3) /* the guest failed an operation */

/* Writes one line to the host console. level is one of LOG_*; other values are treated as LOG_INFO. */
__attribute__((import_module("eden_core"), import_name("log")))
void eden_core_log(int32_t level, const char *message, int32_t message_len);
static inline void eden_core_log_z(int32_t level, const char *message) {
    eden_core_log(level, message, (int32_t)__builtin_strlen(message));
}

/* Monotonic host time in microseconds since the instance was created. */
__attribute__((import_module("eden_core"), import_name("time_us")))
int64_t eden_core_time_us(void);

/* Stops the guest: the running export call fails with this message and the instance becomes faulted. */
__attribute__((import_module("eden_core"), import_name("abort")))
void eden_core_abort(const char *message, int32_t message_len);
static inline void eden_core_abort_z(const char *message) {
    eden_core_abort(message, (int32_t)__builtin_strlen(message));
}

#endif
