/* GENERATED by scripts/abi/abigen.py from abi/idl/eden_input.json - do not edit; change the IDL and regenerate */
#ifndef EDEN_ABI_EDEN_INPUT_H
#define EDEN_ABI_EDEN_INPUT_H

#include <stdint.h>

/* Package eden_input, version 1: Input state sampled by the host once per host frame. Buttons are a device-independent pad the host maps from keyboard and gamepad; keys are PC set-1 scan codes (the values of DirectInput DIK_* and of Eden's KeyCode). */

#define EDEN_INPUT_VERSION 1
#define EDEN_INPUT_BUTTON_A (1) /* pad button A */
#define EDEN_INPUT_BUTTON_B (2) /* pad button B */
#define EDEN_INPUT_BUTTON_SELECT (4) /* pad button Select */
#define EDEN_INPUT_BUTTON_START (8) /* pad button Start */
#define EDEN_INPUT_BUTTON_RIGHT (16) /* d-pad right */
#define EDEN_INPUT_BUTTON_LEFT (32) /* d-pad left */
#define EDEN_INPUT_BUTTON_UP (64) /* d-pad up */
#define EDEN_INPUT_BUTTON_DOWN (128) /* d-pad down */
#define EDEN_INPUT_BUTTON_X (256) /* pad button X */
#define EDEN_INPUT_BUTTON_Y (512) /* pad button Y */
#define EDEN_INPUT_BUTTON_L (1024) /* left shoulder */
#define EDEN_INPUT_BUTTON_R (2048) /* right shoulder */
#define EDEN_INPUT_MOUSE_LEFT (1) /* left mouse button */
#define EDEN_INPUT_MOUSE_RIGHT (2) /* right mouse button */
#define EDEN_INPUT_MOUSE_MIDDLE (4) /* middle mouse button */
#define EDEN_INPUT_AXIS_X (0) /* horizontal mouse axis */
#define EDEN_INPUT_AXIS_Y (1) /* vertical mouse axis, positive down */
#define EDEN_INPUT_AXIS_WHEEL (2) /* mouse wheel */
#define EDEN_INPUT_MAX_SCANCODE (255) /* largest scan code key_down accepts */

/* Held buttons of pad `pad` (0 = the first player) as a BUTTON_* mask; 0 for a pad that does not exist. */
__attribute__((import_module("eden_input"), import_name("buttons")))
int32_t eden_input_buttons(int32_t pad);

/* Whether the key with this set-1 scan code is held; false outside 1..MAX_SCANCODE. */
__attribute__((import_module("eden_input"), import_name("key_down")))
int32_t eden_input_key_down(int32_t scancode);

/* Held mouse buttons as a MOUSE_* mask. */
__attribute__((import_module("eden_input"), import_name("mouse_buttons")))
int32_t eden_input_mouse_buttons(void);

/* Movement of the mouse along AXIS_* since the previous host frame, in pixels (wheel: notches); 0 for an unknown axis. */
__attribute__((import_module("eden_input"), import_name("mouse_delta")))
float eden_input_mouse_delta(int32_t axis);

#endif
