#!/usr/bin/env python3
"""
abigen: the generator of the Eden guest ABI (docs/eden-abi/ABI.md).

Reads abi/idl/*.json (packages) and abi/idl/*.world.json (worlds) and writes:
  source/abi/gen/abi_<package>.das   host bindings of a package: constants,
                                     the implementation struct, one raw-call
                                     wrapper per import, abi_link_<package>
  source/abi/gen/abi_<world>.das     world bindings: abi_bind_<world> and one
                                     typed wrapper per export
  guests/include/eden/<name>.h       the C header of each package and world
  docs/eden-abi/REFERENCE.md         the human-readable reference

Usage (from the repository):
  python3 scripts/abi/abigen.py            write every output
  python3 scripts/abi/abigen.py --check    change nothing; exit 1 if an output
                                           is missing or differs from the IDL
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
IDL = os.path.join(REPO, "abi", "idl")
DAS_OUT = os.path.join(REPO, "source", "abi", "gen")
C_OUT = os.path.join(REPO, "guests", "include", "eden")
DOC_OUT = os.path.join(REPO, "docs", "eden-abi", "REFERENCE.md")
REQUIRE_ROOT = "modules/wasm3das/source/abi"

IDENT = re.compile(r"^[a-z][a-z0-9_]*$")
SCALARS = ["i32", "i64", "f32", "f64", "bool", "handle"]
IMPORT_PARAM_TYPES = SCALARS + ["str", "bytes", "outbuf"]
EXPORT_PARAM_TYPES = SCALARS + ["str", "bytes"]
RESULT_TYPES = ["void"] + SCALARS
DAS_RESERVED = {"type", "string", "var", "let", "def", "struct", "class", "in", "out", "result", "self", "true", "false", "null", "range"}

DAS_TYPE = {"i32": "int", "i64": "int64", "f32": "float", "f64": "double", "bool": "bool",
            "handle": "int", "str": "string", "bytes": "AbiBytes", "outbuf": "AbiBytes", "void": "void"}
DAS_EXPORT_ARG = {"i32": "int", "i64": "int64", "f32": "float", "f64": "double", "bool": "bool",
                  "handle": "int", "str": "string", "bytes": "array<uint8>"}
DAS_DEFAULT = {"i32": "0", "i64": "0l", "f32": "0.0f", "f64": "0.0lf", "bool": "false", "handle": "0"}
SIG_CHAR = {"i32": "i", "i64": "I", "f32": "f", "f64": "F", "bool": "i", "handle": "i", "str": "ii",
            "bytes": "ii", "outbuf": "ii", "void": "v"}
C_TYPE = {"i32": "int32_t", "i64": "int64_t", "f32": "float", "f64": "double", "bool": "int32_t",
          "handle": "int32_t", "void": "void"}
GETTER = {"i32": "m3ApiGetArg_i32(rt, f)", "i64": "m3ApiGetArg_i64(rt, f)", "f32": "m3ApiGetArg_f32(rt, f)",
          "f64": "m3ApiGetArg_f64(rt, f)", "bool": "abi_get_bool(rt, f)", "handle": "m3ApiGetArg_i32(rt, f)"}
RETURNER = {"i32": "m3ApiReturn_i32(rt, raw_return, {v})", "i64": "m3ApiReturn_i64(rt, raw_return, {v})",
            "f32": "m3ApiReturn_f32(rt, raw_return, {v})", "f64": "m3ApiReturn_f64(rt, raw_return, {v})",
            "bool": "m3ApiReturn_i32(rt, raw_return, {v} ? 1 : 0)", "handle": "m3ApiReturn_i32(rt, raw_return, {v})"}
TO_BITS = {"i32": "m3_bits_from_i32({v})", "i64": "m3_bits_from_i64({v})", "f32": "m3_bits_from_f32({v})",
           "f64": "m3_bits_from_f64({v})", "bool": "m3_bits_from_i32({v} ? 1 : 0)", "handle": "m3_bits_from_i32({v})"}
FROM_BITS = {"i32": "m3_bits_to_i32({v})", "i64": "m3_bits_to_i64({v})", "f32": "m3_bits_to_f32({v})",
             "f64": "m3_bits_to_f64({v})", "bool": "(m3_bits_to_i32({v}) != 0)", "handle": "m3_bits_to_i32({v})"}

GEN_NOTE = "GENERATED by scripts/abi/abigen.py from abi/idl/{src} - do not edit; change the IDL and regenerate"


class IdlError(Exception):
    pass


def pascal(name):
    return "".join(p.capitalize() for p in name.split("_"))


def check_ident(what, name):
    if not isinstance(name, str) or not IDENT.match(name):
        raise IdlError("%s: %r is not a lower_snake identifier" % (what, name))


def check_doc(what, obj):
    if not isinstance(obj.get("doc"), str) or not obj["doc"].strip():
        raise IdlError("%s: missing doc" % what)


def load_idl():
    packages, worlds = {}, {}
    for fn in sorted(os.listdir(IDL)):
        if not fn.endswith(".json"):
            continue
        with open(os.path.join(IDL, fn), encoding="utf-8") as f:
            data = json.load(f)
        data["_file"] = fn
        if fn.endswith(".world.json"):
            worlds[data["world"]] = data
        else:
            packages[data["package"]] = data
    return packages, worlds


def validate(packages, worlds):
    for name, p in packages.items():
        where = p["_file"]
        check_ident(where + " package", name)
        if p["_file"] != name + ".json":
            raise IdlError("%s: the file must be named %s.json" % (where, name))
        check_doc(where, p)
        if not isinstance(p.get("version"), int) or p["version"] < 1:
            raise IdlError("%s: version must be a positive integer" % where)
        seen = set()
        for c in p.get("constants", []):
            if not re.match(r"^[A-Z][A-Z0-9_]*$", c["name"]) or not isinstance(c["value"], int):
                raise IdlError("%s: constant %r must be UPPER_SNAKE with an integer value" % (where, c))
            check_doc("%s constant %s" % (where, c["name"]), c)
        for fn in p["functions"]:
            fw = "%s function %s" % (where, fn.get("name"))
            check_ident(fw, fn["name"])
            check_doc(fw, fn)
            if fn["name"] in seen:
                raise IdlError(fw + ": duplicate")
            seen.add(fn["name"])
            pnames = set()
            for prm in fn["params"]:
                check_ident(fw + " param", prm["name"])
                if prm["name"] in pnames:
                    raise IdlError(fw + ": duplicate param " + prm["name"])
                pnames.add(prm["name"])
                if prm["type"] not in IMPORT_PARAM_TYPES:
                    raise IdlError("%s: param %s has type %s; imports take %s" % (fw, prm["name"], prm["type"], IMPORT_PARAM_TYPES))
            if fn["result"] not in RESULT_TYPES:
                raise IdlError("%s: result %s; allowed %s" % (fw, fn["result"], RESULT_TYPES))
    export_owner = {}
    for name, w in worlds.items():
        where = w["_file"]
        check_ident(where + " world", name)
        if w["_file"] != name + ".world.json":
            raise IdlError("%s: the file must be named %s.world.json" % (where, name))
        check_doc(where, w)
        base = w.get("extends")
        if base is not None and base not in worlds:
            raise IdlError("%s: extends unknown world %s" % (where, base))
        for pkg in w["imports"]:
            if pkg not in packages:
                raise IdlError("%s: imports unknown package %s" % (where, pkg))
        for c in w.get("constants", []):
            if not re.match(r"^[A-Z][A-Z0-9_]*$", c["name"]) or not isinstance(c["value"], int):
                raise IdlError("%s: constant %r must be UPPER_SNAKE with an integer value" % (where, c))
        for e in w["exports"]:
            ew = "%s export %s" % (where, e.get("name"))
            check_ident(ew, e["name"])
            check_doc(ew, e)
            if e["name"] in export_owner:
                raise IdlError("%s: export name already used by world %s (export names are unique across worlds)" % (ew, export_owner[e["name"]]))
            export_owner[e["name"]] = name
            if not isinstance(e.get("required"), bool):
                raise IdlError(ew + ": `required` must be true or false")
            for prm in e["params"]:
                check_ident(ew + " param", prm["name"])
                if prm["type"] not in EXPORT_PARAM_TYPES:
                    raise IdlError("%s: param %s has type %s; exports take %s" % (ew, prm["name"], prm["type"], EXPORT_PARAM_TYPES))
            if e["result"] not in RESULT_TYPES:
                raise IdlError("%s: result %s; allowed %s" % (ew, e["result"], RESULT_TYPES))
    for name, w in worlds.items():
        chain = world_chain(worlds, name)
        all_exports = [e for ww in chain for e in ww["exports"]]
        names = {e["name"] for e in all_exports}
        needs_alloc = any(p["type"] in ("str", "bytes") for e in all_exports for p in e["params"])
        if needs_alloc and not {"eden_alloc", "eden_free"} <= names:
            raise IdlError("%s: exports take str/bytes, so the world must declare eden_alloc and eden_free" % w["_file"])


def world_chain(worlds, name):
    """the world and its bases, base first"""
    chain = []
    seen = set()
    while name is not None:
        if name in seen:
            raise IdlError("world %s: extends cycle" % name)
        seen.add(name)
        chain.insert(0, worlds[name])
        name = worlds[name].get("extends")
    return chain


def signature(params, result):
    return SIG_CHAR[result] + "(" + "".join(SIG_CHAR[p["type"]] for p in params) + ")"


def das_comment_block(text, indent=""):
    words = text.split()
    lines, cur = [], ""
    for wd in words:
        if len(cur) + len(wd) + 1 > 74:
            lines.append(cur)
            cur = wd
        else:
            cur = (cur + " " + wd).strip()
    if cur:
        lines.append(cur)
    return "".join("%s// %s\n" % (indent, l) for l in lines)


# ---------------------------------------------------------------------------
# daslang: package
# ---------------------------------------------------------------------------


def gen_das_package(p):
    name = p["package"]
    host = pascal(name) + "Host"
    prefix = name.upper()
    o = []
    o.append("options gen2\noptions indenting = 4\n\n")
    o.append("// " + GEN_NOTE.format(src=p["_file"]) + "\n\n")
    o.append("module abi_%s shared public\n\n" % name)
    o.append("require %s/abi_runtime public\n" % REQUIRE_ROOT)
    o.append("require strings\n\n\n")
    o.append("/*\n    Package %s, version %d: %s\n\n" % (name, p["version"], p["doc"]))
    o.append("    The host implements %s (every field must be set; abi_link_%s\n" % (host, name))
    o.append("    refuses a null one) and links it into an instance. Each\n")
    o.append("    implementation receives the runtime (for AbiBytes access) and the\n")
    o.append("    instance id (the key of any per-instance state it keeps). To fail\n")
    o.append("    the guest it calls abi_trap(message) and returns.\n*/\n\n\n")
    o.append("let public %s_VERSION = %d\n" % (prefix, p["version"]))
    for c in p.get("constants", []):
        o.append("let public %s_%s = %d   // %s\n" % (prefix, c["name"], c["value"], c["doc"]))
    o.append("\n\nstruct %s {\n" % host)
    for fn in p["functions"]:
        o.append(das_comment_block(fn["doc"], "    "))
        args = ["var rt : M3Runtime", "inst : int"] + ["%s : %s" % (a["name"], DAS_TYPE[a["type"]]) for a in fn["params"]]
        o.append("    %s : function<(%s) : %s>\n" % (fn["name"], "; ".join(args), DAS_TYPE[fn["result"]]))
    o.append("}\n\n\n")
    o.append("var private g_impls : table<int; %s>\n\n\n" % host)
    for fn in p["functions"]:
        o.append(gen_das_wrapper(p, fn, host))
    o.append("def private abi_unlink_%s(id : int) {\n    g_impls |> erase(id)\n}\n\n\n" % name)
    o.append("// links every import of %s the guest has; refuses an implementation\n" % name)
    o.append("// with a null function\n")
    o.append("def public abi_link_%s(var inst : AbiInstance; impl : %s) : M3Result {\n" % (name, host))
    o.append("    if (!inst.alive) {\n        return \"{inst.name}: link %s: the instance is not alive\"\n    }\n" % name)
    o.append("    if (abi_is_linked(inst, \"%s\") && !inst.relinking) {\n        return \"{inst.name}: %s is already linked\"\n    }\n" % (name, name))
    o.append("    if (!abi_is_linked(inst, \"%s\") && inst.relinking) {\n        return \"{inst.name}: relink of %s, which was not linked before\"\n    }\n" % (name, name))
    for fn in p["functions"]:
        o.append("    if (impl.%s == null) {\n        return \"{inst.name}: %s.%s has no host implementation\"\n    }\n" % (fn["name"], name, fn["name"]))
    o.append("    g_impls[inst.id] = impl\n")
    o.append("    abi_register_package(inst, \"%s\", @@abi_unlink_%s)\n" % (name, name))
    o.append("    var r : M3Result = m3Err_none\n")
    for fn in p["functions"]:
        o.append("    r = abi_link_one(inst, \"%s\", \"%s\", \"%s\", @@abi_imp_%s_%s)\n" % (name, fn["name"], signature(fn["params"], fn["result"]), name, fn["name"]))
        o.append("    if (r != m3Err_none) {\n        return r\n    }\n")
    o.append("    return m3Err_none\n}\n")
    return "".join(o)


def gen_das_wrapper(p, fn, host):
    name = p["package"]
    o = []
    o.append("// %s.%s %s\n" % (name, fn["name"], signature(fn["params"], fn["result"])))
    o.append("def public abi_imp_%s_%s(var rt : M3Runtime; ctx : M3ImportContext; sp : int) : M3Result {\n" % (name, fn["name"]))
    o.append("    var f = m3ApiFrame(sp)\n")
    if fn["result"] != "void":
        o.append("    let raw_return = m3ApiReturnType(f)\n")
    need_r = any(a["type"] in ("str", "bytes", "outbuf") for a in fn["params"])
    if need_r:
        o.append("    var r : M3Result = m3Err_none\n")
    for a in fn["params"]:
        v = "a_" + a["name"]
        t = a["type"]
        if t == "str":
            o.append("    var %s = \"\"\n    r = abi_get_str(rt, f, %s)\n" % (v, v))
            o.append("    if (r != m3Err_none) {\n        return abi_trap_message(\"%s\", \"%s\", \"%s: {r}\")\n    }\n" % (name, fn["name"], a["name"]))
        elif t in ("bytes", "outbuf"):
            o.append("    var %s = AbiBytes()\n    r = abi_get_bytes(rt, f, %s)\n" % (v, v))
            o.append("    if (r != m3Err_none) {\n        return abi_trap_message(\"%s\", \"%s\", \"%s: {r}\")\n    }\n" % (name, fn["name"], a["name"]))
        else:
            o.append("    let %s = %s\n" % (v, GETTER[t]))
    o.append("    let id = m3_GetUserData(rt)\n")
    o.append("    var impl = %s()\n    var found = false\n" % host)
    o.append("    g_impls |> get(id) $(v) {\n        impl = v\n        found = true\n    }\n")
    o.append("    if (!found) {\n        return abi_trap_message(\"%s\", \"%s\", \"no implementation for instance {id}\")\n    }\n" % (name, fn["name"]))
    call_args = ", ".join(["rt", "id"] + ["a_" + a["name"] for a in fn["params"]])
    if fn["result"] == "void":
        o.append("    invoke(impl.%s, %s)\n" % (fn["name"], call_args))
    else:
        o.append("    let value = invoke(impl.%s, %s)\n" % (fn["name"], call_args))
    o.append("    let trap = abi_take_trap()\n")
    o.append("    if (!empty(trap)) {\n        return abi_trap_message(\"%s\", \"%s\", trap)\n    }\n" % (name, fn["name"]))
    if fn["result"] != "void":
        o.append("    %s\n" % RETURNER[fn["result"]].format(v="value"))
    o.append("    return m3Err_none\n}\n\n\n")
    return "".join(o)


# ---------------------------------------------------------------------------
# daslang: world
# ---------------------------------------------------------------------------


def gen_das_world(w, worlds):
    name = w["world"]
    chain = world_chain(worlds, name)
    prefix = name.upper()
    all_pkgs = [pkg for ww in chain for pkg in ww["imports"]]
    all_exports = [e for ww in chain for e in ww["exports"]]
    version_owner = next((ww for ww in chain if any(e["name"] == "eden_abi_version" for e in ww["exports"])), None)
    o = []
    o.append("options gen2\noptions indenting = 4\n\n")
    o.append("// " + GEN_NOTE.format(src=w["_file"]) + "\n\n")
    o.append("module abi_%s shared public\n\n" % name)
    o.append("require %s/abi_runtime public\n" % REQUIRE_ROOT)
    o.append("require strings\n")
    if w.get("extends"):
        o.append("require %s/gen/abi_%s public\n" % (REQUIRE_ROOT, w["extends"]))
    for pkg in w["imports"]:
        o.append("require %s/gen/abi_%s public\n" % (REQUIRE_ROOT, pkg))
    o.append("\n\n/*\n    World %s, version %d: %s\n" % (name, w["version"], w["doc"]))
    if w.get("extends"):
        o.append("    Extends %s.\n" % w["extends"])
    o.append("\n    Packages: %s.\n" % ", ".join(all_pkgs))
    o.append("    After linking the packages, abi_bind_%s checks the imports, finds\n" % name)
    o.append("    the exports and the version; the abi_<export> functions call them.\n*/\n\n\n")
    o.append("let public %s_VERSION = %d\n" % (prefix, w["version"]))
    for c in w.get("constants", []):
        o.append("let public %s_%s = %d   // %s\n" % (prefix, c["name"], c["value"], c["doc"]))
    o.append("\n\n")
    for e in w["exports"]:
        o.append(gen_das_export(e))
    req = [e["name"] for e in all_exports if e["required"]]
    opt = [e["name"] for e in all_exports if not e["required"]]
    o.append("// imports resolved and in the world, required exports present, version\n")
    o.append("def public abi_bind_%s(var inst : AbiInstance) : M3Result {\n" % name)
    o.append("    if (!inst.alive) {\n        return \"{inst.name}: bind %s: the instance is not alive\"\n    }\n" % name)
    o.append("    var packages : array<string>\n")
    for pkg in all_pkgs:
        o.append("    push(packages, \"%s\")\n" % pkg)
    o.append("    var r = abi_check_imports(inst, \"%s\", packages)\n" % name)
    o.append("    if (r != m3Err_none) {\n        return r\n    }\n")
    o.append("    var required : array<string>\n    var optional : array<string>\n")
    for n in req:
        o.append("    push(required, \"%s\")\n" % n)
    for n in opt:
        o.append("    push(optional, \"%s\")\n" % n)
    o.append("    r = abi_bind_exports(inst, required, optional)\n")
    o.append("    if (r != m3Err_none) {\n        return r\n    }\n")
    if version_owner is not None:
        o.append("    let version = abi_eden_abi_version(inst)\n")
        o.append("    if (!empty(inst.error)) {\n        return inst.error\n    }\n")
        o.append("    if (version != %d) {\n        return \"{inst.name}: built for world version {version}, the host supports %s version %d\"\n    }\n"
                 % (version_owner["version"], version_owner["world"], version_owner["version"]))
    o.append("    inst.world = \"%s\"\n    return m3Err_none\n}\n" % name)
    return "".join(o)


def gen_das_export(e):
    params = e["params"]
    res = e["result"]
    args = ["var inst : AbiInstance"] + ["a_%s : %s" % (p["name"], DAS_EXPORT_ARG[p["type"]]) for p in params]
    ret = "" if res == "void" else " : " + DAS_TYPE[res]
    fail = "return" if res == "void" else "return " + DAS_DEFAULT[res]
    o = []
    o.append(das_comment_block(e["doc"] + (" Optional export: check abi_has_export first." if not e["required"] else "")))
    o.append("// On failure returns %s and inst.error says why.\n" % ("nothing" if res == "void" else DAS_DEFAULT[res]))
    o.append("def public abi_%s(%s)%s {\n" % (e["name"], "; ".join(args), ret))
    o.append("    if (!inst.faulted) {\n        inst.error = \"\"\n    }\n")
    # inscope: the temporaries are freed at the end of the call (the script
    # heap is only collected between engine frames)
    o.append("    var inscope args : array<uint64>\n")
    placed = [p for p in params if p["type"] in ("str", "bytes")]
    if placed:
        o.append("    var inscope placed : array<int>\n")
    for p in params:
        v = "a_" + p["name"]
        if p["type"] in ("str", "bytes"):
            placer = "abi_place_str" if p["type"] == "str" else "abi_place_bytes"
            o.append("    let p_%s = %s(inst, %s)\n" % (p["name"], placer, v))
            o.append("    if (p_%s == 0) {\n" % p["name"])
            o.append("        for (q in placed) {\n            abi_free_guest(inst, q)\n        }\n")
            o.append("        %s\n    }\n" % fail)
            o.append("    push(placed, p_%s)\n" % p["name"])
            o.append("    push(args, m3_bits_from_i32(p_%s))\n" % p["name"])
            o.append("    push(args, m3_bits_from_i32(length(%s)))\n" % v)
        else:
            o.append("    push(args, %s)\n" % TO_BITS[p["type"]].format(v=v))
    o.append("    var inscope rets : array<uint64>\n")
    o.append("    let ok = abi_call(inst, \"%s\", args, rets)\n" % e["name"])
    if placed:
        o.append("    for (q in placed) {\n        abi_free_guest(inst, q)\n    }\n")
    if res == "void":
        o.append("    if (!ok) {\n        return\n    }\n")
    else:
        o.append("    if (!ok || length(rets) < 1) {\n        return %s\n    }\n" % DAS_DEFAULT[res])
        o.append("    return %s\n" % FROM_BITS[res].format(v="rets[0]"))
    o.append("}\n\n\n")
    return "".join(o)


# ---------------------------------------------------------------------------
# C headers
# ---------------------------------------------------------------------------


def c_params(params, const_bytes=True):
    out = []
    for p in params:
        t = p["type"]
        if t == "str":
            out += ["const char *%s" % p["name"], "int32_t %s_len" % p["name"]]
        elif t == "bytes":
            out += ["const void *%s" % p["name"], "int32_t %s_len" % p["name"]]
        elif t == "outbuf":
            out += ["void *%s" % p["name"], "int32_t %s_cap" % p["name"]]
        else:
            out.append("%s %s" % (C_TYPE[t], p["name"]))
    return ", ".join(out) if out else "void"


def c_comment(text, indent=""):
    return "%s/* %s */\n" % (indent, text)


def gen_c_package(p):
    name = p["package"]
    guard = "EDEN_ABI_%s_H" % name.upper()
    prefix = name.upper()
    o = []
    o.append("/* " + GEN_NOTE.format(src=p["_file"]) + " */\n")
    o.append("#ifndef %s\n#define %s\n\n#include <stdint.h>\n\n" % (guard, guard))
    o.append(c_comment("Package %s, version %d: %s" % (name, p["version"], p["doc"])))
    o.append("\n#define %s_VERSION %d\n" % (prefix, p["version"]))
    for c in p.get("constants", []):
        o.append("#define %s_%s (%d) /* %s */\n" % (prefix, c["name"], c["value"], c["doc"]))
    o.append("\n")
    for fn in p["functions"]:
        o.append(c_comment(fn["doc"]))
        o.append("__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n" % (name, fn["name"]))
        o.append("%s %s_%s(%s);\n" % (C_TYPE[fn["result"]], name, fn["name"], c_params(fn["params"])))
        strs = [a for a in fn["params"] if a["type"] == "str"]
        if strs:
            cp, call = [], []
            for a in fn["params"]:
                if a["type"] == "str":
                    cp.append("const char *%s" % a["name"])
                    call += [a["name"], "(int32_t)__builtin_strlen(%s)" % a["name"]]
                elif a["type"] == "bytes":
                    cp += ["const void *%s" % a["name"], "int32_t %s_len" % a["name"]]
                    call += [a["name"], a["name"] + "_len"]
                elif a["type"] == "outbuf":
                    cp += ["void *%s" % a["name"], "int32_t %s_cap" % a["name"]]
                    call += [a["name"], a["name"] + "_cap"]
                else:
                    cp.append("%s %s" % (C_TYPE[a["type"]], a["name"]))
                    call.append(a["name"])
            ret = "" if fn["result"] == "void" else "return "
            o.append("static inline %s %s_%s_z(%s) {\n    %s%s_%s(%s);\n}\n" % (
                C_TYPE[fn["result"]], name, fn["name"], ", ".join(cp), ret, name, fn["name"], ", ".join(call)))
        o.append("\n")
    o.append("#endif\n")
    return "".join(o)


def gen_c_world(w, worlds):
    name = w["world"]
    guard = "EDEN_ABI_%s_H" % name.upper()
    prefix = name.upper()
    o = []
    o.append("/* " + GEN_NOTE.format(src=w["_file"]) + " */\n")
    o.append("#ifndef %s\n#define %s\n\n#include <stdint.h>\n" % (guard, guard))
    if w.get("extends"):
        o.append("#include \"%s.h\"\n" % w["extends"])
    for pkg in w["imports"]:
        o.append("#include \"%s.h\"\n" % pkg)
    o.append("\n" + c_comment("World %s, version %d: %s The guest defines the exports below." % (name, w["version"], w["doc"])))
    o.append("\n#define %s_VERSION %d\n" % (prefix, w["version"]))
    for c in w.get("constants", []):
        o.append("#define %s_%s (%d) /* %s */\n" % (prefix, c["name"], c["value"], c["doc"]))
    o.append("\n")
    for e in w["exports"]:
        o.append(c_comment(e["doc"] + ("" if e["required"] else " (optional)")))
        o.append("__attribute__((export_name(\"%s\")))\n" % e["name"])
        o.append("%s %s(%s);\n\n" % (C_TYPE[e["result"]], e["name"], c_params(e["params"])))
    o.append("#endif\n")
    return "".join(o)


# ---------------------------------------------------------------------------
# Reference
# ---------------------------------------------------------------------------


def md_params(params):
    return ", ".join("%s: %s" % (p["name"], p["type"]) for p in params)


def gen_reference(packages, worlds):
    o = ["# Eden guest ABI reference\n\n",
         "<!-- " + GEN_NOTE.format(src="*.json") + " -->\n\n",
         "The rules behind these tables are in `ABI.md`.\n\n"]
    for name in sorted(worlds):
        w = worlds[name]
        o.append("## World `%s` v%d\n\n%s\n\n" % (name, w["version"], w["doc"]))
        if w.get("extends"):
            o.append("Extends `%s`.\n\n" % w["extends"])
        o.append("Packages: %s.\n\n" % ", ".join("`%s`" % p for p in w["imports"]))
        o.append("| Export | Required | Doc |\n| --- | --- | --- |\n")
        for e in w["exports"]:
            o.append("| `%s(%s) -> %s` | %s | %s |\n" % (e["name"], md_params(e["params"]), e["result"], "yes" if e["required"] else "no", e["doc"]))
        o.append("\n")
        for c in w.get("constants", []):
            o.append("- `%s_%s = %d`: %s\n" % (name.upper(), c["name"], c["value"], c["doc"]))
        o.append("\n")
    for name in sorted(packages):
        p = packages[name]
        o.append("## Package `%s` v%d\n\n%s\n\n" % (name, p["version"], p["doc"]))
        o.append("| Import | Doc |\n| --- | --- |\n")
        for fn in p["functions"]:
            o.append("| `%s(%s) -> %s` | %s |\n" % (fn["name"], md_params(fn["params"]), fn["result"], fn["doc"]))
        o.append("\n")
        for c in p.get("constants", []):
            o.append("- `%s_%s = %d`: %s\n" % (name.upper(), c["name"], c["value"], c["doc"]))
        o.append("\n")
    return "".join(o)


def outputs(packages, worlds):
    out = {}
    for name, p in packages.items():
        out[os.path.join(DAS_OUT, "abi_%s.das" % name)] = gen_das_package(p)
        out[os.path.join(C_OUT, "%s.h" % name)] = gen_c_package(p)
    for name, w in worlds.items():
        out[os.path.join(DAS_OUT, "abi_%s.das" % name)] = gen_das_world(w, worlds)
        out[os.path.join(C_OUT, "%s.h" % name)] = gen_c_world(w, worlds)
    out[DOC_OUT] = gen_reference(packages, worlds)
    return out


def main():
    check = "--check" in sys.argv[1:]
    try:
        packages, worlds = load_idl()
        validate(packages, worlds)
    except (IdlError, KeyError, ValueError) as e:
        print("abigen: IDL error: %s" % e)
        return 2
    out = outputs(packages, worlds)
    stale = []
    for path, text in sorted(out.items()):
        old = None
        if os.path.exists(path):
            with open(path, encoding="utf-8", newline="") as f:
                old = f.read()
        if old != text:
            stale.append(os.path.relpath(path, REPO))
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(text)
    managed = {os.path.normpath(p) for p in out}
    extra = []
    for d, ext in ((DAS_OUT, ".das"), (C_OUT, ".h")):
        if os.path.isdir(d):
            for fn in os.listdir(d):
                p = os.path.normpath(os.path.join(d, fn))
                if fn.endswith(ext) and p not in managed:
                    extra.append(os.path.relpath(p, REPO))
    if check:
        for s in stale:
            print("abigen: out of date: %s" % s)
        for s in extra:
            print("abigen: not produced by the IDL (delete it): %s" % s)
        if stale or extra:
            print("abigen: run python3 scripts/abi/abigen.py")
            return 1
        print("abigen: up to date (%d packages, %d worlds, %d files)" % (len(packages), len(worlds), len(out)))
        return 0
    for s in stale:
        print("abigen: wrote %s" % s)
    for s in extra:
        print("abigen: warning: stale generated file not produced by the IDL: %s" % s)
    print("abigen: %d packages, %d worlds, %d files (%d changed)" % (len(packages), len(worlds), len(out), len(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
